# Generated by Django 2.0.2 on 2018-03-15 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet_name', models.CharField(max_length=200)),
                ('owner_name', models.CharField(max_length=200)),
                ('admission_date', models.DateTimeField(verbose_name='Date of admission')),
            ],
        ),
        migrations.CreateModel(
            name='Charge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('standard', models.CharField(max_length=1000)),
                ('note', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('duty', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Hospitalization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admissionID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic_structure.Admission')),
            ],
        ),
        migrations.CreateModel(
            name='LaboratoryTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('standard', models.CharField(max_length=1000)),
                ('note', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_date', models.DateTimeField(verbose_name='Record Date')),
                ('status', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('Title', models.CharField(max_length=200)),
                ('birthday', models.DateTimeField(verbose_name='Birthday')),
            ],
        ),
        migrations.AddField(
            model_name='hospitalization',
            name='recordID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic_structure.Record'),
        ),
        migrations.AddField(
            model_name='department',
            name='leaderID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic_structure.Staff'),
        ),
        migrations.AddField(
            model_name='admission',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_id', to='basic_structure.Staff'),
        ),
        migrations.AddField(
            model_name='admission',
            name='nurse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nurse_id', to='basic_structure.Staff'),
        ),
        migrations.AlterUniqueTogether(
            name='hospitalization',
            unique_together={('admissionID', 'recordID')},
        ),
    ]
